Aws assume
maruina/go-infrabin pull request #159
Opened 2021-11-23 13:31 UTC by maruina

This PR introduces a breaking change. The AWS endpoint now takes two subpaths:
- `/aws/metadata/$path` has the old `/aws/$path` feature to access AWS metadata
- `/aws/assume/$role_arn` tells go-infrabin to try to assume the AWS role calling STS Assume Role

In addition:
- remove `dependabot` as superseeded by Renovate

2021-11-23 13:53 UTC, janeklb commented on internal/aws/clients.go
> +}
Can this be moved into a test package / module / file?

2021-11-23 15:03 UTC, janeklb commented on internal/aws/clients.go
> +}
no i mean into something totally separate -- just for tests.. maybe in test helper package/ module?

2021-11-29 16:22 UTC, Smirl requested changes
Should update the README?

2021-11-29 16:33 UTC, Smirl commented on README.md
> +* _grpc_: `infrabin.Infrabin.AWSAssume` _rest_: `GET /aws/assume/<path>`
```suggestion
* _grpc_: `infrabin.Infrabin.AWSAssume` _rest_: `GET /aws/assume/<role>`
```

2021-11-29 16:34 UTC, Smirl commented on README.md
> +  * _returns_: JSON with the AssumedRoleId from AWS
We give examples for other known response types. a little example would be nice

2021-11-29 16:51 UTC, Smirl approved these changes
LGTM

2021-11-29 16:54 UTC, merged